# ~/.config/starship.toml

# Use custom format

format = '''
[┌─\( $username$hostname$directory$git_status\)](bold green)
[└─>](bold green)
'''

scan_timeout = 10    # Wait 10 milliseconds for starship to check files under the current directory.
add_newline = false  # Disable the blank line at the start of the prompt
palette = 'foo'      # Set 'foo' as custom color palette

[username]
show_always = true

[git]
show_always = true

[palettes.foo]       # Define custom colors
blue = '21'          # Overwrite existing color
mustard = '#af8700'  # Define new color

[fill]
symbol = ' '

[time]
disabled = false


